name: Continuous Delivery

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0-23 * * *"

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: install, build, lint and test
        run: |
          npm ci
          npm run bootstrap
          npm run build
          npm run lint
          npm run test

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: packages/storybook
