name: Lint & Test

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: npm install, lint, and test
        run: |
          npm ci
          npm run bootstrap
          npm run lint --if-present
          npm run test --if-present
